# Generated by Django 5.0.2 on 2024-05-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
