# Generated by Django 5.0.2 on 2024-03-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('password', models.CharField(max_length=20, verbose_name='пароль')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('age', models.IntegerField(verbose_name='возраст')),
                ('gender', models.CharField(max_length=7, verbose_name='пол')),
            ],
        ),
    ]
